eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: error-ttVehicle-getVehicle
          uri: lb://error-login-service
          predicates:
            - Path=/ttvehicle/getAll
          filters:
            - AuthenticationFilter
          metadata:
            requiredRole: "LEADER"
        - id: error-ttVehicle
          uri: lb://error-login-service
          predicates:
            - Path=/ttvehicle/**
          filters:
            - AuthenticationFilter
          metadata:
            requiredRole: "OPERATOR"
        - id: error-ttDefect-getDefects
          uri: lb://error-login-service
          predicates:
            - Path=/ttvehicleDefect/getAll
          filters:
            - AuthenticationFilter
          metadata:
            requiredRole: "LEADER"
        - id: error-ttDefect-getImage
          uri: lb://error-login-service
          predicates:
            - Path=/ttvehicleDefect/get/image/**
          filters:
            - AuthenticationFilter
          metadata:
            requiredRole: "LEADER"
        - id: error-ttDefect
          uri: lb://error-login-service
          predicates:
            - Path=/ttvehicleDefect/**
          filters:
            - AuthenticationFilter
          metadata:
            requiredRole: "OPERATOR"
        - id: error-location
          uri: lb://error-login-service
          predicates:
            - Path=/defectLocation/**
          filters:
            - AuthenticationFilter
          metadata:
            requiredRole: "OPERATOR"
        - id: error-list
          uri: lb://error-listing-service
          predicates:
            - Path=/errors/**
          filters:
            - AuthenticationFilter
          metadata:
            requiredRole: "LEADER"
        - id: terminal-service
          uri: lb://terminal-service
          predicates:
            - Path=/terminal/**
          filters:
            - AuthenticationFilter
          metadata:
            requiredRole: ""
        - id:  verification-authorization-service
          uri: lb://verification-authorization-service
          predicates:
            - Path=/auth/**

        - id:  user-management-service
          uri: lb://user-management-service
          predicates:
            - Path=/user-management/**
          filters:
            - AuthenticationFilter
          metadata:
            requiredRole: "ADMIN"

