eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: error-ttVehicle-getVehicle
          uri: lb://error-login-service
          predicates:
            - Path=/vehicle/getAll
          filters:
            - AuthenticationFilter
          metadata:
            requiredRole: "LEADER"
        - id: error-ttVehicle
          uri: lb://error-login-service
          predicates:
            - Path=/vehicle/**
          filters:
            - AuthenticationFilter
          metadata:
            requiredRole: "OPERATOR"
        - id: error-ttDefect-getDefects
          uri: lb://error-login-service
          predicates:
            - Path=/defect/getAll
          filters:
            - AuthenticationFilter
          metadata:
            requiredRole: "LEADER"
        - id: error-ttDefect-getImage
          uri: lb://error-login-service
          predicates:
            - Path=/defect/{defectImage}/get/image
          filters:
            - AuthenticationFilter
          metadata:
            requiredRole: "LEADER"
        - id: error-ttDefect
          uri: lb://error-login-service
          predicates:
            - Path=/defect/**
          filters:
            - AuthenticationFilter
          metadata:
            requiredRole: "OPERATOR"
        - id: error-location
          uri: lb://error-login-service
          predicates:
            - Path=/location/**
          filters:
            - AuthenticationFilter
          metadata:
            requiredRole: "OPERATOR"
        - id: error-list
          uri: lb://error-listing-service
          predicates:
            - Path=/list/**
          filters:
            - AuthenticationFilter
          metadata:
            requiredRole: "LEADER"
        - id: terminal-service
          uri: lb://terminal-service
          predicates:
            - Path=/terminal/**
          filters:
            - AuthenticationFilter
          metadata:
            requiredRole: ""
        - id:  verification-authorization-service
          uri: lb://verification-authorization-service
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter
          metadata:
            requiredRole: "ADMIN"

        - id:  user-management-service
          uri: lb://user-management-service
          predicates:
            - Path=/user-management/**
          filters:
            - AuthenticationFilter
          metadata:
            requiredRole: "ADMIN"

